version: '3.7'


services:
  web:
    image: slave_web
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    networks:
      custom-network:
        ipv4_address: 192.168.100.3
    entrypoint: ["sh", "-c", "/app/init_routes.sh && python manage.py runserver 0.0.0.0:8000"]
    restart: always

  wireguard-client:
    image: linuxserver/wireguard
    container_name: wireguard-client
    networks:
      custom-network:
        ipv4_address: 192.168.100.2
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
      - ./enable_forwarding.sh:/etc/enable_forwarding.sh
    entrypoint: ["/bin/sh", "-c", "/etc/enable_forwarding.sh && /init"]
    ports:
      - 51820:51820/udp
    dns:
      - 1.1.1.1
      - 8.8.8.8
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

networks:
  custom-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
